version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost/api
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.api
    ports:
      - "80:80"
    environment:
      - INVOICE_PROCESSOR_URL=http://invoice_processor:5001
    networks:
      - app-network

  invoice_processor:
    build:
      context: ./backend
      dockerfile: Dockerfile.invoice
    ports:
      - "5001:5001"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge