version: '3.8'

services:
  frontend:
    image: alvee25/pet-frontend:latest
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    ports:
      - "3000:80"
    networks:
      - pet-network

  backend:
    image: alvee25/pet-backend:latest
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    ports:
      - "8000:8000"
    networks:
      - pet-network
    environment:
      - AI_PROCESSOR_URL=http://ai-processor:8001

  ai-processor:
    image: alvee25/pet-ai-processor:latest
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    ports:
      - "8001:8001"
    networks:
      - pet-network

networks:
  pet-network:
    driver: overlay