FROM python:3.11

RUN pip3 install poetry

WORKDIR /app

COPY pyproject.toml poetry.lock ./

RUN poetry install --no-root

COPY ai_invoice_processor ai_invoice_processor

EXPOSE 8001

CMD ["poetry", "run", "gunicorn", "--timeout", "0", "--bind", "0.0.0.0:8001", "ai_invoice_processor:create_app()"]