FROM python:3.11

RUN pip3 install poetry

WORKDIR /app

COPY pyproject.toml poetry.lock ./

RUN poetry install --no-root

COPY PETbackend PETbackend

EXPOSE 8000 

# Changed to use gunicorn instead of Flask development server
CMD ["poetry", "run", "gunicorn", "--bind", "0.0.0.0:8000", "PETbackend:create_app()"]